version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development  # Use development stage
    ports:
      - "3001:3001"  # Express API
      - "8080:8080"  # WebSocket server
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    volumes:
      # Mount source for development hot reload
      - ./backend/src:/app/src:ro
      - ./backend/united_airlines_normalized\ \(Gauntlet\).db:/app/united_airlines_normalized\ \(Gauntlet\).db:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3001/health').then(() => process.exit(0)).catch(() => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development  # Use development stage
    ports:
      - "5173:5173"  # Vite dev server
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=http://localhost:3001
      - VITE_WS_URL=ws://localhost:8080
    volumes:
      # Mount source for development hot reload
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
    restart: unless-stopped
    depends_on:
      - backend

networks:
  default:
    name: frontier-audio-network
